[tool.black]
line-length = 80
target-version = ["py312"]
skip-string-normalization = true
fast = false
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \__pycache__
  | \.venv
  | build
  | dist
)/  
'''
preview = true

[tool.ruff]
line-length = 88
exclude = ["venv", "migrations"]

[tool.ruff.lint]
ignore = ["E501"]
select = ["E", "F"]

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["fastapi"]
known_first_party = ["SummarizeXpress"]
src_paths = ["src"]